unit BridgeCommon;

interface

const
  STEAM2BRIDGE_INTERFACE_VERSION_001 = 'STEAM2BRIDGE_INTERFACE_VERSION001';
  STEAM2BRIDGE_INTERFACE_VERSION_002 = 'STEAM2BRIDGE_INTERFACE_VERSION002';

implementation

end.
